version: '3.8'
services:
  app:  # Tu backend de Spring Boot
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/lista-tareas
    depends_on:
      - mongodb

  mongodb:  # Tu base de datos MongoDB
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  next-app:  # Tu aplicación Next.js
    build: ./my-app-next  # Asegúrate de actualizar esta ruta
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: yarn start  # Comando para ejecutar la aplicación
    depends_on:
      - app  # Si tu aplicación Next.js depende del backend de Spring Boot

volumes:
  mongodb_data:
